# Generated by Django 4.1.2 on 2022-10-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apuntes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('contenido', models.CharField(max_length=300)),
            ],
        ),
    ]
