# Generated by Django 4.1.2 on 2022-10-31 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0003_alter_apuntes_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='apuntes',
            name='cedula',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUno.contacto'),
            preserve_default=False,
        ),
    ]
