# Generated by Django 4.1.2 on 2022-11-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0004_apuntes_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuntes',
            name='contenido',
            field=models.CharField(max_length=100),
        ),
    ]
