# Generated by Django 4.1.2 on 2022-11-03 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0005_alter_apuntes_contenido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'ordering': ['id'], 'verbose_name': 'Contacto', 'verbose_name_plural': 'contactos'},
        ),
        migrations.AlterModelTable(
            name='contacto',
            table='contac',
        ),
    ]
