# Generated by Django 4.1.2 on 2022-11-03 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0006_alter_contacto_options_alter_contacto_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apuntes',
            name='cedula',
        ),
        migrations.AddField(
            model_name='apuntes',
            name='email',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='appUno.contacto', verbose_name='Nota del contacto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apuntes',
            name='contenido',
            field=models.TextField(verbose_name='Contenido de la nota'),
        ),
        migrations.AlterField(
            model_name='apuntes',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
