# Generated by Django 4.1.2 on 2022-11-03 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUno', '0007_remove_apuntes_cedula_apuntes_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apuntes',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appUno.contacto', verbose_name='Nota del contacto'),
        ),
    ]
